### ISSUE TITLE
Problem s seštevanjem

### ISSUE THREAD

**Issue by matejske** [matejske/APPR-2019-20#1]
Pozdravljeni!

Pri uvozu sem želel ustvariti nov stolpec v tabeli "skupno.plini", ki bi bil seštevek prejšnjih treh stolpcev, a mi jih ne sešteje pravilno.

Hvala in lep pozdrav.

**Comment by jaanos** [comment]
Problem se pojavi že pri uvozu razpredelnice `emisije` - ker se za ločila tisočic uporabljajo presledki, se zadnji stolpec ne prebere pravilno. Svetujem, da namesto `read.csv` (s piko) uporabiš funkcijo `read_csv` (s podčrtajem) iz knjižnice `readr` (tudi pri ostalih uvozih) - potem bi šlo nekako tako:
```R
emisije <- read_csv('podatki/emisije.csv', na=c(":", " ", "", "-"), skip=1,
                    locale=locale(grouping_mark=" ", encoding="Windows-1250"),
                    col_names=c("Enota", "Drzava", "Leto", "Merjen.plin",
                                "Sector.gospodarstva", "Izpuscene.emisije"))
```
Po brisanju sumarnih podatkov je razpredelnica `emisije` že v obliki *tidy data*, tako da razpredelnica `skupno.plini` ni potrebna (razen morda za prikaz podatkov - v tem primeru si lahko pomagaš s funkcijo `spread` iz knjižnice `tidyr`). Tudi vsote ni smiselno imeti v razpredelnici, pač pa jo lahko sproti izračunaš (npr. pri izrisovanju grafa):
```R
emisije %>% group_by(Drzava, Leto, Sector.gospodarstva) %>%
  summarise(Skupne.emisije=sum(Izpuscene.emisije, na.rm=TRUE))
```
