### ISSUE TITLE
Primerjava držav

### ISSUE THREAD

**Issue by matejske** [matejske/APPR-2019-20#2]
Pozdravljeni,

zanima me kako iz tabele "europe" pofiltrirati ven samo države EU, vsebovane v bdp$Drzava, z enostavno funkcijo, brez da bi to moral delati ročno.

Hvala.

**Comment by jaanos** [comment]
Za filtriranje lahko uporabiš operator `%in%`, npr.
```R
drzave_eu <- europe %>% filter(NAME %in% bdp$Drzava)
```
Vendar pa bodo v zemljevidu, narisanem iz takih podatkov, luknje. Namesto tega raje podatkom pri risanju zemljevida pridruži `europe` z `right_join`, da se izrišejo tudi države, za katere nimaš podatkov, npr.
```R
ggplot() + geom_polygon(data=bdp %>% filter(Leto == 2017) %>%
                          right_join(europe, by=c("Drzava"="NAME")),
                        aes(x=long, y=lat, group=group, fill=BDP.E))
```
Seveda se morajo imena držav ujemati (po potrebi jih lahko popraviš v podatkih ali zemljevidu).
