### ISSUE TITLE
Prošnja za predloge

### ISSUE THREAD

**Issue by matejske** [matejske/APPR-2019-20#4]
Spoštovani,

prosil bi vas, če lahko pregledate projekt in mi podate morebitne predloge za izboljšave in predloge, kaj bi še lahko naredil, preden začnem z estetskimi popravki kode in grafov, ter pisanjem Markdown-a.

V naprej hvala in lepo pozdravljeni,
Matej Škerlep

**Comment by jaanos** [comment]
Trenutno grafe izrisuješ v `vizualizacija.r` - namesto tega jih izrisuj v poročilu na želenih mestih. Iz `vizualizacija.r` in `analiza.r` tudi odstrani klice programov `libraries.r` in `uvoz.r`, saj se bodo ti med prevajanjem poročila že predhodno pognali.

Trenutno se sklicuješ na spremenljivko `zemljevid.bdp.2017`, ki ni definirana - verjetno si hotel izrisati zemljevid za leto 2016. Pri tem zemljevidu poskrbi, da se v legendi ne bo pojavljala eksponentna notacije - podatke deli z npr. 1000000 in ustrezno popravi naslov legende (prištej npr. `guides(fill=guide_colorbar("BDP v milijonih €"))`). Enako naredi tudi za zemljevid v aplikaciji Shiny. Na podoben način lahko popraviš še naslov legende na ostalih grafih (pri zemljevidu skupin namesto `guide_colorbar` uporabi `guide_legend`).

Tudi pri grafu povezave med davki in emisijami poskrbi, da se eksponentna notacija ne bo pojavljala na osi y (ter ustrezno popravi oznake na oseh - tudi na drugih grafih). Pri grafu napovedi svetujem, da točke iz napovedi izrišeš z drugo barvo in nad črto napovedi (`geom_point` premakni za `geom_smooth`). Sicer pa lahko na slednjem grafu opaziš, da nekatere podatkovne točke padejo izven območja napake, kar kaže na to, da prileganje ni ravno najboljše.

Še to: poskrbi za ustrezne povezave za Binder v `README.md`:
https://github.com/matejske/APPR-2019-20/blob/0a7565b3b69f1afdecec0eb9e19fff18f2ba8313/README.md#L5-L6
Tukaj torej nadomesti `jaanos` z `matejske`. Ko bo pripravljeno poročilo, ga bo tako mogoče poganjati kar v brskalniku.

**Comment by matejske** [comment]
Pozdravljeni,

hvala za zgornje komentarje. Vse sem upošteval in naredil popravke, nato pa sem grafe tudi izrisal v poročilu. V poročilo moram seveda dodati še svoja opažanja.

Prosil bi vas, če lahko pogledate, zakaj se mi v Markdown-u plotly graf iz "vizualizacija.r" ne izrisuje.
(koda za izpis plotlyja je v Mardownu v 111. vrstici)

Če imate še kakšne komentarje, kaj bi lahko izboljšal in dopolnil, mi prosim sporočite.

Hvala in lep pozdrav,
Matej Škerlep

**Comment by jaanos** [comment]
Da se ti izriše graf, ga izpiši brez funkcije `print` - torej samo s `plotly.graf2`.

Drugih komentarjev nimam, tako da sporoči, ko bo dokončano poročilo.

**Comment by jaanos** [comment]
Glede na korespondenco z @alenFMF sklepam, da si s projektom končal. Poročilo se prevede, tako da bom dodal povezavo na repozitorij za zagovore in se tako lahko domeniš tudi za termin zagovora. Če boš do takrat še kaj spreminjal, mi javi, da posodobim povezavo.

Imam samo eno pripombo estetske narave. Pri meni se graf s `plotly` izriše zelo široko (širše kot preostanek poročila, tudi, če maksimiziram okno) - svetujem, da pri `ggplotly` dodaš še parameter `width=1000`, da graf ne bo preširok tudi pri manjših ločljivostih. Poleg tega se pri podatkih za vsako točko (če greš z miško čez) ime države izpiše dvakrat - sklepam, da se v podatkih pojavi dvakrat, tako da lahko eno od pojavitev odstraniš. Legendo lahko prav tako odstraniš, saj je v bistvu nepotrebna, poleg tega pa se ne prikaže v celoti.
