### ISSUE TITLE
Funkcija html

### ISSUE THREAD

**Issue by matejske** [matejske/APPR-2019-20#5]
Pozdravljeni,

kot sva se pogovarjala sem se odločil, da bom namesto csv-ja BDP-jem raja uvozil podatke iz html-ja. Podatke sem sprva skušal uvoziti kot html iz [Eurostata](https://appsso.eurostat.ec.europa.eu/nui/show.do?dataset=nama_10_gdp&lang=en),  a mi R javi, da ne more uvoziti tabele, ker naj menda sploh ne bi bila v obliki html.

Nato sem na [Wikipediji](https://en.wikipedia.org/wiki/List_of_countries_by_GDP_(nominal)) našel tabelo z BDP-ji, ki bi bila prav tako v redu. Napisano imam tudi funkcijo za uvoz html-ja, a mi noče z interneta pobrati tabele. 

Funkcija se nahaja v ''uvoz_html.r''. Prosil bi vas, če boste lahko ogledali, kaj manjka, da bo funkcija delovala.

V naprej se vam zahvaljujem in vas lepo pozdravljam,
Matej Škerlep

**Comment by jaanos** [comment]
Trenutno je problem tukaj:
https://github.com/matejske/APPR-2019-20/blob/f7b6ce25c20cc8e9de7f282d0aca7ceb5bb7ff37/uvoz/uvoz_html.r#L6-L7
Če želiš navesti niz znotraj sintakse *XPath*, bo potrebno poskrbeti, da ga navedeš znotraj R-jevega niza - če je ta razmejen z dvojnimi navednicami, znotraj njega uporabi enojne navednice, saj se bo sicer R-jev niz končal in bo prišlo do skladenjske napake.

Sicer pa z zgornjim izrazom zajameš tabelo, v kateri so gnezdene tri tabele s podatki, zaradi česar uvoz ne bo deloval pravilno. Lažje bo, če se lotiš vsake tabele posebej (oziroma tistih, ki jih potrebuješ). Vse tri tabele imajo nastavljen atribut `class` na `wikitable sortable`, tako da jih lahko tako identificiraš. Prvo tabelo lahko potem uvoziš tako:
```R
  bruto.domaci.proizvod <- stran %>% html_node(xpath="//table[@class='wikitable sortable'][1]") %>% 
    html_table()
```
Seveda bo potrebno podatke še prečistiti: pri državah odstraniti opombe, GDP pa pretvoriti v števila (uporabi `parse_number` z ustrezno nastavitvijo ločila tisočic).

**Comment by matejske** [comment]
Pozdravljeni,

sem dodal tudi tabelo iz html-ja. Naredil sem tudi nekaj estetskih popravkov in do konca spisal poročilo. 

Pri shiny aplikaciji sem fiksiral skalo, da se ob spreminjanju vhodnih podatkov funkcije ne spreminja. Tu se mi pojavi estetski problem, saj so si v primeru nizkih vrednosti emisij barve na zemljevidu med sabo zelo podobne. Zanima me, kaj predlagate, kako bi lahko to izboljšal.

Sicer pa menim, da sem s projektom dokončno zaključil, tako da vas prosim, da po tem ko odpravim estetski izgled shinyja, posodobite povezavo do repozitorija, da se lahko prijavim na zagovor k profesorju.

Hvala in lepo pozdravljeni,
Matej Škerlep

**Comment by jaanos** [comment]
Ena možnost bi bila, da skalo fiksiraš samo glede na izbrani sektor - najprej torej samo fiksiraš sektor in pridobiš maksimalno vrednost, nato pa naprej filtriraš še po letu, da dobiš podatke za izris.

Ko boš imel pripravljeno končno različico, prosim povej, da posodobim povezavo.

**Comment by matejske** [comment]
Pozdravljeni,

sem naredil kot ste predlagali, a ker podatki po sektorjih precej nihajo, potem prihaja do eksponentne notacije pri nekaterih sektorjih, pri drugih pa do zapisa vrednosti s po 8 števkami. Zato sem zgolj barvo za spodnjo mejo še nekoliko posvetlil, da je bolj opazna razlika na skali.

Tako, da imam sedaj končno različico in vas prosim, če lahko posodobite povezavo.

Še enkrat bi se vam rad zahvalil za vso pomoč in nasvete pri projektu.

Matej Škerlep

**Comment by jaanos** [comment]
V redu, sem posodobil povezavo.
